---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kemuning/baralek/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R audio $DEPLOYPATH
