---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kemuning/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R audio $DEPLOYPATH
